version: '3.8'

services:
  neo4j:
    image: quay.io/lib/neo4j:latest
    container_name: iroko-neo4j
    hostname: neo4j
    ports:
      - "7474:7474"  # Browser interface
      - "7687:7687"  # Bolt protocol
    volumes:
      - neo4j_data:/data:Z
      - neo4j_logs:/logs:Z
      - neo4j_plugins:/plugins:Z
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_dbms_default__database=${NEO4J_DATABASE}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "${NEO4J_PASSWORD}", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - iroko-net
    restart: unless-stopped
    # ulimits:
    #   nofile:
    #     soft: 40000
    #     hard: 40000c
  

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_plugins:
    driver: local
    
networks:
  iroko-net:
    driver: bridge
    attachable: true
    labels:
      - description="Isolated network for repo-semedo services"